import type { Field, Model } from './calculator-types.ts';
import { FT_PER_M, LB_PER_KG, allowance, count, fmt, length, netArea, number, openings, positiveOrZero, price, rectangle, requireCondition, result, roundUp, row, volume, waste, withCost } from './calculator-math.ts';

const quikrete='https://www.quikrete.com/calculator/main.asp';
const cmha='https://www.cmha.org/resource/tek-04-02a/';
const geometry='https://www.calculatorsoup.com/calculators/construction/concrete-calculator.php';
export const densityField:Field={...number('density','Material density',150,undefined,'Example bulk density. Replace with a supplier value for the same moisture and compaction condition.'),unit:'lb/ft3',units:['lb/ft3','kg/m3','ton/yd3'],group:'Material & assumptions'};
export function densityLb(v:number,unit:string){return unit==='kg/m3'?v*LB_PER_KG/FT_PER_M**3:unit==='ton/yd3'?v*2000/27:v;}
const yieldField:Field={...volume('yield','Mixed yield per bag',0.6),unit:'ft3',group:'Material & assumptions',help:'Read the yield printed on the bag. 0.60 ft³ is an example for an 80 lb standard concrete mix, not every product.'};
const concreteFields=[allowance,densityField,yieldField,price('USD/yd3',['USD/yd3','USD/m3','USD/ft3','USD/bag'])];
function concreteResult(cuFt:number,v:Record<string,number>,u:Record<string,string>,steps:string[]){
  const total=cuFt*waste(v),bags=roundUp(total/v.yield),lb=total*densityLb(v.density,u.density),rows=[row('order','Concrete to order',total/27,'yd³'),row('net','Geometric volume',cuFt/27,'yd³'),row('ft3','Order volume',total,'ft³'),row('m3','Order volume',total/FT_PER_M**3,'m³'),row('bags','Bags at entered yield',bags,'bags',true),row('weight','Estimated order weight',lb,'lb'),row('tons','Estimated order weight',lb/2000,'US tons')];
  withCost(rows,v.price,u.price,{'USD/yd3':total/27,'USD/m3':total/FT_PER_M**3,'USD/ft3':total,'USD/bag':bags});
  return result(rows,[...steps,`Apply ${fmt(v.waste)}% allowance: ${fmt(cuFt)} × ${fmt(waste(v))} = ${fmt(total)} ft³.`,`Bags: round ${fmt(total)} ÷ ${fmt(v.yield)} up to ${bags}.`],['Bag yield is mixed concrete volume; bag mass is not the weight of cured concrete.']);
}
function concreteModel(fields:Field[],formula:string,assumptions:string[],calc:(v:Record<string,number>)=>number):Model{
  return {fields:[...fields,...concreteFields],formula,assumptions,sources:[geometry,quikrete],calculate(v,u){const cuFt=calc(v);return concreteResult(cuFt,v,u,[`${formula}. Dimensions converted to feet: net volume = ${fmt(cuFt)} ft³.`]);}};
}
const layerFields=[...rectangle,length('depth','Placed thickness',4,'in'),count('quantity','Identical sections',1)];
const mixFields=[volume('volume','Required mixed volume',1),number('dryFactor','Dry volume / mixed volume',1.54,1,'Planning assumption for aggregate voids. Use a trial batch or specified mix yield.'),number('cement','Cement parts',1),number('sand','Sand parts',2),number('aggregate','Coarse aggregate parts',3,0),number('cementDensity','Loose cement density (kg/m³)',1440),number('bagMass','Cement bag mass (kg)',50),allowance];
const mix:Model={fields:mixFields,formula:'Dry volume = mixed volume × dry factor; ingredient volume = dry volume × ingredient parts / total parts; cement mass = cement volume × bulk density.',assumptions:['Ratios are by loose dry volume, not mass. A nominal ratio does not establish concrete strength, durability or a water/cement ratio.','For structural concrete, order the specified mix or obtain an approved mix design. Water and admixtures are not estimated.'],sources:[quikrete],calculate(v){const mixed=v.volume*waste(v),dry=mixed*v.dryFactor,total=v.cement+v.sand+v.aggregate;const cement=dry*v.cement/total,sand=dry*v.sand/total,aggregate=dry*v.aggregate/total,kg=cement/FT_PER_M**3*v.cementDensity;return result([row('cementMass','Loose cement mass',kg,'kg'),row('bags','Whole cement bags',roundUp(kg/v.bagMass),'bags',true),row('sand','Dry sand volume',sand/FT_PER_M**3,'m³'),row('aggregate','Dry coarse aggregate volume',aggregate/FT_PER_M**3,'m³'),row('mixed','Mixed volume including allowance',mixed/FT_PER_M**3,'m³')],[`Parts: ${fmt(v.cement)} + ${fmt(v.sand)} + ${fmt(v.aggregate)} = ${fmt(total)}.`,`Dry material volume: ${fmt(mixed/FT_PER_M**3)} × ${fmt(v.dryFactor)} = ${fmt(dry/FT_PER_M**3)} m³.`,`Cement: ${fmt(cement/FT_PER_M**3)} m³ × ${fmt(v.cementDensity)} kg/m³ = ${fmt(kg)} kg.`]);}};
const bulk:Model={fields:[...layerFields,{...densityField,value:1.4,unit:'ton/yd3'},allowance,price('USD/yd3',['USD/yd3','USD/m3','USD/ton'])],formula:'Volume = length × width × depth × sections; order volume = volume × (1 + allowance / 100); weight = order volume × density.',assumptions:['Depth and density must describe the same state: loose delivered material or the finished compacted layer.','Density varies with grading, moisture and compaction. A supplier quote is more reliable than a generic default. Short tons are 2,000 lb.'],sources:['https://www.engineeringtoolbox.com/density-materials-d_1652.html'],calculate(v,u){const net=v.length*v.width*v.depth*v.quantity,order=net*waste(v),lb=order*densityLb(v.density,u.density);return result(withCost([row('order','Material volume with allowance',order/27,'yd³'),row('tons','Estimated order weight',lb/2000,'US tons'),row('net','Net placed volume',net/27,'yd³'),row('m3','Order volume',order/FT_PER_M**3,'m³'),row('weight','Order weight',lb/LB_PER_KG,'kg')],v.price,u.price,{'USD/yd3':order/27,'USD/m3':order/FT_PER_M**3,'USD/ton':lb/2000}),[`Net: ${fmt(v.length)} × ${fmt(v.width)} × ${fmt(v.depth)} × ${v.quantity} = ${fmt(net)} ft³.`,`With ${v.waste}% allowance: ${fmt(order)} ft³ ÷ 27 = ${fmt(order/27)} yd³.`,`Weight: ${fmt(order)} ft³ × ${fmt(densityLb(v.density,u.density))} lb/ft³ = ${fmt(lb)} lb.`]);}};
const weight:Model={...bulk,fields:[volume(),densityField,allowance,price('USD/ton',['USD/ton','USD/yd3'])],formula:'Mass = volume × density; US tons = pounds / 2,000; kilograms = pounds × 0.45359237.',calculate(v,u){const cuFt=v.volume,order=cuFt*waste(v),lb=order*densityLb(v.density,u.density);return result(withCost([row('weight','Estimated weight',lb,'lb'),row('tons','US short tons',lb/2000,'US tons'),row('tonnes','Metric tonnes',lb/LB_PER_KG/1000,'tonnes'),row('order','Volume including allowance',order/27,'yd³')],v.price,u.price,{'USD/ton':lb/2000,'USD/yd3':order/27}),[`${fmt(cuFt)} ft³ × ${fmt(waste(v))} = ${fmt(order)} ft³.`,`${fmt(order)} × ${fmt(densityLb(v.density,u.density))} lb/ft³ = ${fmt(lb)} lb.`]);}};
const depth:Model={fields:[...rectangle,volume()],formula:'Average depth = volume / (length × width).',assumptions:['This calculates coverage depth from an available volume. It does not choose a structurally adequate slab or pavement thickness.','Volume and area must refer to the same placed or compacted condition.'],sources:[geometry],calculate(v){const area=v.length*v.width,depth=v.volume/area;return result([row('depth','Average depth',depth*12,'in'),row('mm','Average depth',depth/FT_PER_M*1000,'mm'),row('area','Covered area',area,'ft²')],[`${fmt(v.volume)} ft³ ÷ ${fmt(area)} ft² = ${fmt(depth)} ft.`,`Convert feet to inches: ${fmt(depth)} × 12 = ${fmt(depth*12)} in.`]);}};
const masonry:Model={fields:[length('length','Wall length',20),length('width','Wall height',8),openings,length('unitLength','Actual unit length',7.625,'in'),length('unitHeight','Actual unit height',2.25,'in'),positiveOrZero(length('joint','Mortar joint',0.375,'in')),allowance,number('unitWeight','Unit weight (lb)',4.3),price('USD/unit')],formula:'Net wall area = length × height − openings; units = ceil(net area × allowance factor / ((unit length + joint) × (unit height + joint))).',assumptions:['Use the exposed face dimensions, not the unit depth. Defaults describe one wythe of modular brick.','A nominal 16 × 8 in CMU face includes its joints: enter actual dimensions 15⅝ × 7⅝ in with a ⅜ in joint.','This is an area estimate. Corners, returns, lintels, bond patterns, caps and special units require a separate takeoff.'],sources:[cmha],calculate(v,u){const area=netArea(v),face=(v.unitLength+v.joint)*(v.unitHeight+v.joint),raw=area/face,n=roundUp(raw*waste(v));return result(withCost([row('units','Units to order',n,'units',true),row('area','Net wall area',area,'ft²'),row('base','Units without allowance',roundUp(raw),'units',true),row('perArea','Units per square foot',1/face,'units/ft²'),row('weight','Unmortared unit weight',n*v.unitWeight,'lb')],v.price,u.price,{'USD/unit':n}),[`Net area: ${fmt(v.length*v.width)} − ${fmt(v.openings)} = ${fmt(area)} ft².`,`Installed module: ${fmt((v.unitLength+v.joint)*12)} × ${fmt((v.unitHeight+v.joint)*12)} in.`,`Round ${fmt(raw)} × ${fmt(waste(v))} up once = ${n} units.`]);}};
const bags:Model={fields:[volume(),yieldField,allowance,price('USD/bag')],formula:'Bags = ceil(required mixed volume × allowance factor / mixed yield per bag).',assumptions:['Use mixed yield from the product data sheet; bags of equal mass can have different yields.','This estimates a known volume. It does not select a mortar type or grout specification.'],sources:[quikrete],calculate(v,u){const order=v.volume*waste(v),n=roundUp(order/v.yield);return result(withCost([row('bags','Whole bags to order',n,'bags',true),row('order','Mixed volume including allowance',order,'ft³'),row('m3','Mixed volume',order/FT_PER_M**3,'m³')],v.price,u.price,{'USD/bag':n}),[`${fmt(v.volume)} × ${fmt(waste(v))} = ${fmt(order)} ft³.`,`Round ${fmt(order)} ÷ ${fmt(v.yield)} up = ${n} bags.`]);}};

export const materialModels:Record<string,Model>={
  concrete:concreteModel(layerFields,'V = length × width × thickness × identical sections',['Rectangular sections of uniform thickness. Split irregular shapes into non-overlapping rectangles.','Thickness and reinforcement must come from project plans; volume alone does not establish load capacity.'],v=>v.length*v.width*v.depth*v.quantity),
  wall:concreteModel([length('length','Total wall length',40),length('height','Wall height',8),length('thickness','Wall thickness',8,'in'),{...volume('openings','Volume of openings',0),min:0}],'V = wall length × height × thickness − opening volume',['Enter the combined centerline length of wall runs so corners are not counted twice.','Subtract door and window volume; footing and slab quantities are separate.'],v=>{const n=v.length*v.height*v.thickness-v.openings;requireCondition(n>=0,'openings','Openings cannot exceed the wall volume.');return n;}),
  cylinder:concreteModel([length('diameter','Diameter',12,'in'),length('height','Height / depth',8),count('quantity','Number of identical cylinders')],'V = π × (diameter / 2)² × height × quantity',['Use the diameter, not the radius.','A form diameter estimates concrete volume; it does not select an adequate footing size or embedment.'],v=>Math.PI*(v.diameter/2)**2*v.height*v.quantity),
  tube:concreteModel([length('diameter','Outer diameter',12,'in'),positiveOrZero(length('inner','Inner diameter (zero for solid)',0,'in')),length('height','Height / length',8),count('quantity','Identical tubes')],'V = π / 4 × (outer diameter² − inner diameter²) × height × quantity',['A solid form has inner diameter zero. The inner diameter must be smaller than the outer diameter.'],v=>{requireCondition(v.inner<v.diameter,'inner','Inner diameter must be smaller than outer diameter.');return Math.PI/4*(v.diameter**2-v.inner**2)*v.height*v.quantity;}),
  curb:concreteModel([length(),length('curbWidth','Curb width',6,'in'),length('curbHeight','Full curb height',12,'in'),positiveOrZero(length('gutterWidth','Gutter width beyond curb',18,'in')),length('gutterDepth','Gutter thickness',6,'in')],'V = length × (curb width × full curb height + gutter width beyond curb × gutter thickness)',['The two cross-section rectangles must not overlap. Measure gutter width beyond the curb, excluding curb width.','For a tapered gutter or shaped curb, use the actual cross-section area from the section drawing.'],v=>v.length*(v.curbWidth*v.curbHeight+v.gutterWidth*v.gutterDepth)),
  stairs:concreteModel([length('width','Stair width',4),length('rise','Rise of each step',7,'in'),length('run','Tread depth of each step',11,'in'),count('steps','Number of equal steps',4),positiveOrZero(length('landing','Additional landing length beyond top tread',0))],'V = width × rise × run × n(n + 1) / 2 + width × landing length × n × rise',['Solid steps filled from a level base. Each succeeding tread section is one riser taller.','The additional landing is at the top elevation and excludes the top tread. Open or soil-filled stairs need a different section takeoff.'],v=>v.width*v.rise*v.run*v.steps*(v.steps+1)/2+v.width*v.landing*v.steps*v.rise),
  ramp:concreteModel([...rectangle,positiveOrZero(length('low','Thickness at low end',0,'in')),length('high','Thickness at high end',6,'in')],'V = horizontal length × width × (low thickness + high thickness) / 2',['A straight ramp with linearly varying thickness. Enter horizontal plan length, not sloping surface length.'],v=>{requireCondition(v.high>=v.low,'high','High-end thickness must be at least the low-end thickness.');return v.length*v.width*(v.low+v.high)/2;}),
  bulk, weight, depth, mix, masonry, bags,
  'asphalt-depth':{...depth,fields:[...rectangle,{id:'mass',label:'Asphalt mass',value:10,unit:'ton',units:['ton','tonne','lb','kg'],dimension:'weight'},densityField],formula:'Compacted thickness = mass / (compacted density × area).',calculate(v,u){return depth.calculate({...v,volume:v.mass/densityLb(v.density,u.density)},u);}},
  'brick-mortar':{fields:[...masonry.fields.filter(f=>!['price','unitWeight'].includes(f.id)),length('wythe','Mortar bedding depth',3.625,'in'),yieldField,price('USD/bag')],formula:'Mortar volume ≈ net wall area × bedding depth × (1 − actual brick face / installed module face).',assumptions:['Geometric estimate for full-bed, single-wythe brickwork, including bed and head joints. Frogs, perforations and site losses affect actual yield.','Do not apply solid brick bedding geometry to hollow CMU face-shell bedding.'],sources:[cmha,quikrete],calculate(v,u){const a=netArea(v),fraction=1-v.unitLength*v.unitHeight/((v.unitLength+v.joint)*(v.unitHeight+v.joint)),cuFt=a*v.wythe*fraction;return bags.calculate({...v,volume:cuFt},u);}},
  'cmu-mortar':{fields:[number('units','Number of installed blocks',113,0),number('coverage','Installed blocks per bag',13,undefined,'Use the mortar manufacturer’s yield for the block size and bedding method.'),allowance,price('USD/bag')],formula:'Mortar bags = ceil(installed blocks × allowance factor / blocks per bag).',assumptions:['Coverage must refer to a complete premixed mortar bag. A bag of masonry cement alone requires additional sand.','Full-bed and face-shell bedding have different mortar requirements.'],sources:[cmha,quikrete],calculate(v,u){const n=roundUp(v.units*waste(v)/v.coverage);return result(withCost([row('bags','Mortar bags',n,'bags',true)],v.price,u.price,{'USD/bag':n}),[`Round ${v.units} × ${fmt(waste(v))} ÷ ${v.coverage} up = ${n} bags.`]);}},
  'cmu-grout':{fields:[count('units','Blocks receiving grout',100,0),{...volume('cellVolume','Grouted void volume per block',0.25),unit:'ft3',help:'Use the block manufacturer’s core volume for the cells actually filled. The example is not universal.'},allowance,price('USD/yd3')],formula:'Grout volume = grouted blocks × grouted void volume per block × allowance factor.',assumptions:['Count only cells to be filled. Bond beams, pilasters and special units require separate volume allowances.','Grout is the core fill; mortar is the joint material.'],sources:[cmha],calculate(v,u){const cuFt=v.units*v.cellVolume*waste(v);return result(withCost([row('order','Grout to order',cuFt/27,'yd³'),row('ft3','Grout volume',cuFt,'ft³'),row('m3','Grout volume',cuFt/FT_PER_M**3,'m³')],v.price,u.price,{'USD/yd3':cuFt/27}),[`${v.units} × ${fmt(v.cellVolume)} × ${fmt(waste(v))} = ${fmt(cuFt)} ft³.`]);}},
  'brick-joint':{fields:[length('length','Finished course length',10),length('unitLength','Actual brick length',7.625,'in'),count('units','Bricks in the course',15,2)],formula:'Joint width = (course length − brick count × actual brick length) / (brick count − 1).',assumptions:['One straight course with joints only between bricks. End joints and expansion joints are excluded.','A geometric fit is not a recommendation to exceed the specified joint tolerance.'],sources:[cmha],calculate(v){const joint=(v.length-v.units*v.unitLength)/(v.units-1);requireCondition(joint>=0,'units','The bricks are longer than this course even without joints. Reduce the count or increase the course length.');return result([row('joint','Equal joint width',joint*12,'in'),row('mm','Equal joint width',joint/FT_PER_M*1000,'mm')],[`(${fmt(v.length*12)} − ${v.units} × ${fmt(v.unitLength*12)}) ÷ ${v.units-1} = ${fmt(joint*12)} in.`]);}},
  'material-cost':{fields:[number('quantity','Material quantity',100,0),{...price('USD/unit'),optional:false},number('delivery','Delivery charge ($)',0,0),number('labor','Labor charge ($)',0,0),number('tax','Tax on material (%)',0,0),allowance],formula:'Total = quantity × allowance factor × unit price × (1 + material tax / 100) + delivery + labor.',assumptions:['Quantity and quoted unit price must use the same unit. Tax applies to materials only in this model; local treatment of services and delivery may differ.','Use a separate calculation for each material line and add the totals.'],sources:[],calculate(v){const q=v.quantity*waste(v),materials=q*v.price,total=materials*(1+v.tax/100)+v.delivery+v.labor;return result([row('cost','Estimated total',total,'USD'),row('materials','Material subtotal',materials,'USD'),row('quantity','Quantity including allowance',q,'units'),row('tax','Material tax',materials*v.tax/100,'USD')],[`${fmt(q)} units × $${fmt(v.price)} = $${fmt(materials)}.`,`Add material tax, $${fmt(v.delivery)} delivery and $${fmt(v.labor)} labor.`]);}},
  waste:{fields:[number('quantity','Net quantity',100,0),allowance],formula:'Extra quantity = net quantity × allowance / 100; total = net quantity + extra.',assumptions:['Keep the same unit throughout. For discrete items, use the whole-item total; do not round intermediate quantities.'],sources:[],calculate(v){const total=v.quantity*waste(v);return result([row('total','Total including allowance',total,'units'),row('extra','Extra quantity',total-v.quantity,'units'),row('whole','Whole items to order',roundUp(total),'items',true)],[`${fmt(v.quantity)} × ${fmt(v.waste/100)} = ${fmt(total-v.quantity)} extra.`,`${fmt(v.quantity)} + ${fmt(total-v.quantity)} = ${fmt(total)} total.`]);}},
};
